# Generated by Django 5.1.4 on 2024-12-19 17:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=datetime.time(0, 0))),
                ('location', models.IntegerField(choices=[(0, 'Langland'), (1, 'Caswell'), (2, 'Llangennith'), (3, 'Oxwich'), (4, 'Hunts'), (5, 'Three Cliffs')], default=0)),
                ('wave_height', models.PositiveIntegerField()),
                ('wind_direction', models.IntegerField(choices=[(0, 'N'), (1, 'NE'), (2, 'E'), (3, 'SE'), (4, 'S'), (5, 'SW'), (6, 'W'), (7, 'NW')], default=0)),
                ('wind_speed', models.PositiveIntegerField()),
                ('tide', models.IntegerField(choices=[(0, 'High'), (1, 'Mid'), (2, 'Low')], default=0)),
                ('surfboard_used', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.IntegerField(choices=[(0, '*'), (1, '**'), (2, '***'), (3, '****'), (4, '*****')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surf_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
