# Generated by Django 5.1.4 on 2024-12-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surf_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['date', 'time']},
        ),
    ]
